# Infrastructure
# - Defines the vCenter / vSphere environment
deploy_vsphere_vcenter: 'vcenter.akaicloud.com'
deploy_vsphere_user: 'administrator@akaicloud.com'
deploy_vsphere_password: 'password'
deploy_vsphere_datacenter: 'Datacenter'
deploy_vsphere_folder: 'Datacenter/vm/Zabbix Cluster Test'
deploy_vsphere_cluster: 'Cluster01'
deploy_vsphere_resourcepool: 'Zabbix Test'

# Guest
# - Describes virtual machine common options
guest_network: 'management'
guest_netmask: '255.255.255.0'
guest_gateway: '192.168.128.1'
guest_dns_server: '192.168.125.53'
guest_domain_name: 'akaicloud.com'
guest_id: 'ubuntu64Guest'
guest_memory: '4096'
guest_vcpu: '2'
#guest_template: ''
guest_wait_for_ip_address: 'yes'
guest_state: 'poweredon'
